default:
    just --list

run:
    parallel --line-buffer --halt now,fail=1 ::: \
      "cargo run --features reload" \
      "cargo watch -w systems -w components -x 'build -p systems --features dynamic'"
