[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "hot-iced"
version = "0.1.0"
edition = "2024"

[dependencies]
hot-lib-reloader = "0.6.2"
iced = { version = "0.6", features = ["smol"] }
lib = { version = "0.1.0", path = "lib" }
