[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "*"
hot-lib-reloader = { path = "../.." }
lib = { path = "lib" }
log = "*"
